import Head from 'next/head'
import {BsFillMoonStarsFill,BsStackOverflow , BsGithub,BsFillFileEarmarkPdfFill} from "react-icons/bs";
import {AiFillLinkedin} from "react-icons/ai";
import Image from  "next/image";
import dev from "../public/avatar.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";

export default function Home() {
    const [darkmode, setDarkMode] = useState(false)
    const navigateURL =  (url) =>{
        console.log(url)
        window.open(url, '_blank').focus();
    }
  return (
    <div className={darkmode ? "dark":""}>
      <Head>
        <title>Williams Chinwa Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-black pb-20">
          <section className="min-h-screen">
              {/*Start Navigation section*/}
              <nav className="py-10 mb-12 flex justify-between">
                    <h1 className="text-xl font-burtons">Developed by Williams Chinwa</h1>
                    <ul className="flex items-center">
                        <li>
                            <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkmode)} className="cursor-pointer text-2xl   dark:text-white"/>
                        </li>
                        <li>
                            {/*<Link to="https://l.linklyhq.com/l/1WET9">*/}
                            {/*    <button className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 border-none rounded ml-8" >Resume</button>*/}
                            {/*</Link>*/}
                        </li>
                        <li>
                            {/*<AiFillLinkedin className="text-4xl text-blue-700 ml-4" />*/}
                            {/*<a className="bg-gradient-to-r from-blue-500 to-blue-500 bg-blue-500 text-white px-4 py-2 border-none rounded ml-8" href="https://l.linklyhq.com/l/1WE3H">LinkedIn</a>*/}
                        </li>
                    </ul>
              </nav>
              {/*Close Navigation section*/}

              {/* User Profile Section Start*/}
              <div className="text-center p-10 ">

                  <h2 className="text-5xl py-2 text-teal-600 font-medium">Williams Chinwa</h2>
                  <h3 className={"text-2xl py-2 md:text-3xl  dark:text-white"}>Fullstack Developer</h3>
                  <p className={"text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto   dark:text-white"}>Diligent software engineer with 4+ years of experience in commercial application and software development. I love to build innovative and cutting-edge business solutions for the impressive suite of clients within its global reach. In previous roles, slashed downtime by 25% and ensured 98% on-time project completion. Also identified and dealt with a significant process bottleneck that boosted coding efficiency by 35% when resolved.</p>
              </div>
              {/* User Profile Section end*/}

              {/*Social links sections start*/}
              <div className={"text-5xl flex justify-center gap-16 py-3 text-gray-600"}>
                  {/*<Link to="https://stackoverflow.com/users/6828297/c-williams">*/}
                  {/*    <BsStackOverflow className={"text-4xl text-yellow-600 cursor-pointer"} />*/}
                  {/*</Link>*/}
                  <BsFillFileEarmarkPdfFill  className={"text-5xl text-red-600 cursor-pointer"} onClick={()=>navigateURL('https://l.linklyhq.com/l/1WET9')} />
                  <BsStackOverflow className={"text-5xl text-yellow-600 cursor-pointer   dark:text-white"}  onClick={()=>navigateURL('https://l.linklyhq.com/l/1WF1G')} />
                  <AiFillLinkedin className="text-5xl text-blue-700 ml-4 cursor-pointer   dark:text-white" onClick={()=>navigateURL('https://l.linklyhq.com/l/1WE3H')} />
                  <BsGithub className={"text-5xl text-gray-600  cursor-pointer   dark:text-white"} onClick={()=>navigateURL('https://l.linklyhq.com/l/1WF3a')}></BsGithub>
              </div>
              {/*Social links sections end*/}

          {/*    Profile image section */}
              <div className={"relative mx-auto  bg-gradient-to-b from-teal-500  rounded-full w-80 h-80  mt-20 overflow-hidden md:h-96 md:w-96"}>
                  <Image src={dev} layout="fill" objectFit="cover" />
              </div>

          {/*    End of Profile image section*/}
          </section>

          {/*Projects section*/}
          <section>
              <div>
                  <h3 className={"text-3xl py-1"}>My Journey</h3>
                  <p className={"text-md py-2 leading-8 text-gray-800   dark:text-white"}>When I first started as a <span className={"text-teal-600"}>full stack developer</span>, I worked on a number of projects that were used by more than <span className={"text-teal-600"}>150k users</span>  . I have also led teams in developing systems that adhere to <span className={"text-teal-600"}> best practises</span> for the industry. With numerous <span className={"text-teal-600"}>AWS cloud computing services</span> , including RDS, elastic beanstalk, EC2, VPC, and many others. I also have experience with <span className={"text-teal-600"}>mobile development</span>  and have developed native apps for  <span className={"text-teal-600"}> IOS and Android</span>  that are utilised by more than <span className={"text-teal-600"}> 25k</span>  mobile devices.</p>
              </div>

              <div className={"flex flex-col lg:flex-row lg:gap-5 "}>
                  {/*project */}
                  <div className={"text-center shadow-lg p-10 rounded-xl my-10  flex-1 dark:text-white dark:border-2 dark:border-white"}>
                      <Image src={design} width={100}  height={100}/>
                      <h3 className={"text-lg font-medium pt-8 pb-2"}>Beautiful Designs</h3>
                      <p className={"py-2   dark:text-white"}>
                          Creating elegant designs  following core design theory and converting UI/UX to HTML/CSS .
                      </p>
                      <h4 className={"text-teal-600 py-4   dark:text-white"}>Design, Javascript & CSS tools used</h4>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Adobe XD</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Figma </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Tailwind</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Bootstrap</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> ReactJS </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> VueJS</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Typescript</p>

                  </div>
                  {/*end of project*/}


                  {/*project */}
                  <div className={"text-center shadow-lg p-10 rounded-xl my-10  flex-1   dark:text-white dark:border-2 dark:border-white"}>
                      <Image src={code} width={100}  height={100}/>
                      <h3 className={"text-lg font-medium pt-8 pb-2"}>Backend Development, Unit Testing and Infrastructure</h3>
                      <p className={"py-2"}>
                          Analyse user requirements. write and test code,refining and rewriting it as necessary and communicate with any programmers involved in the project
                      </p>
                      <h4 className={"text-teal-600 py-4   dark:text-white"}>LAMP</h4>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Docker </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> AWS RDS </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> REST API and Documentation</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Bash </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Linux and Ubuntu</p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> TDD Unit Testing with PhpUnit, Jest</p>
                  </div>
                  {/*end of project*/}


                  {/*project */}
                  <div className={"text-center shadow-lg p-10 rounded-xl my-10  flex-1 dark:text-white dark:border-2 dark:border-white"}>
                      <Image src={consulting} width={100}  height={100}/>
                      <h3 className={"text-lg font-medium pt-8 pb-2"}>System design</h3>
                      <p className={"py-2   dark:text-white"}>
                          Define elements of a system like modules, architecture, components and their interfaces and data for a system based on the specified requirements
                      </p>
                      <h4 className={"text-teal-600 py-4   dark:text-white"}>Agile Methodology</h4>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Object Oriented Programming  </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> UML and Flowcharts  </p>
                      <p className={"text-gray-800 py-1   dark:text-white"}> Github</p>
                  </div>
                  {/*end of project*/}

              </div>


              {/* end of Projects section*/}
          </section>

      {/*    */}
          <section>
              <h3 className={"text-3xl py-1 mb-4"}>Portfolio </h3>
              <div className={"grid grid-cols-1 gap-4  lg:grid-cols-2 lg:gap-8  "}>
                  <div className={"w-full " }>
                      <Image src={web1} layout="responsive" objectFit="cover"  width={"100%"} height={"100%"}  className={"  rounded-lg "} />
                  </div>
                  <div className={"w-full " }>
                      <Image src={web2} layout="responsive" objectFit="cover"  width={"100%"} height={"100%"}  className={"  rounded-lg "} />
                  </div>
                  <div className={"w-full " }>
                      <Image src={web3} layout="responsive" objectFit="cover"  width={"100%"} height={"100%"}  className={"  rounded-lg "}  />
                  </div>
                  <div className={"w-full " }>
                      <Image src={web4} layout="responsive" objectFit="cover"  width={"100%"} height={"100%"}  className={"  rounded-lg "}  />
                  </div>
                  <div className={"w-full " }>
                      <Image src={web5} layout="responsive" objectFit="cover"  width={"100%"} height={"100%"}  className={"  rounded-lg "}  />
                  </div>


                  {/*<Image className={"  rounded-lg "} objectFit={"cover"}  width={"100"} height={"500"} src={web2}/>*/}
                  {/*<Image className={"  rounded-lg "} objectFit={"cover"}  width={"100"} height={"500"} src={web3}/>*/}
                  {/*<Image className={"  rounded-lg "} objectFit={"cover"}  width={"100"} height={"500"} src={web4}/>*/}
                  {/*<Image className={"  rounded-lg "} objectFit={"cover"}  width={"100"} height={"500"} src={web5}/>*/}
                  {/*<Image className={"  rounded-lg "} objectFit={"cover"}  width={"100"} height={"500"} src={web6}/>*/}
              </div>
          </section>

      </main>
    </div>

  )
}
